remove css, add re-export, add ES6 improvment
Sanya486/currency-converter-react-app pull request #1
Opened 2023-09-22 11:21 UTC by Sanya486

2023-09-22 11:25 UTC, Sanya486 commented
Думав про Сітку. Я розумію що це, просто так як в мене тільки один елемент я її не використовув. 
Адаптив в мене реалізується за допомогою Container(компонент реакт - бутстрап). А респонсив на мобільній верстці за допомогою того, що встановлено max-width на елементи які потрібно щоб стискалися.

2023-09-26 08:15 UTC, mike-gusiev requested changes

2023-09-26 08:15 UTC, mike-gusiev commented on src/api/fetchExchangeRates.js
> +    console.log(response)
крапка з комою не завжди стоїть у тебе. постав собі eslint і налаштуй його щоб він перевіряв усі відступи і пунктуації

2023-09-26 08:15 UTC, mike-gusiev commented on src/api/fetchExchangeRates.js
> +}
перед відправкою пул реквеста на рев'ю переглядай файли свого пул реквесту на гітхабі. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2023-09-26 08:15 UTC, mike-gusiev commented on src/components/ConverterForm.jsx
> +// import PropTypes from 'prop-types'
не зберігай закоментованний код в репозиторії

2023-09-26 08:15 UTC, mike-gusiev commented on src/components/CurrencySelector.jsx
> +import {
погрупуй імпорти. спочатку будуть іти імпорти бібліотек, потім відступ, потім імпорти компонентів, потім відступ, потім імпорт всього іншого

2023-09-26 08:15 UTC, mike-gusiev commented on src/components/CurrencyTable.jsx
> +const currentCurrency = useSelector(selectCurrency)
відступи неправильні, крапок з комою немає

2023-09-26 08:15 UTC, mike-gusiev commented on src/components/Tabs.jsx
> +
зайвий перенос рядка

2023-09-26 08:15 UTC, mike-gusiev commented on src/globalStyles.js
> +
зайвий перенос

2023-09-26 08:15 UTC, mike-gusiev commented on src/redux/sagas.js
> +import { call, put, takeEvery } from 'redux-saga/effects'
структура редаксу трохи неправильна.і створи папку src/redux/ducks. і туди в окремі файли помісти усі екшени/редюсери/саги і тд одним файлом. все що відноситься до одного duck - має бути в одному файлі:
https://github.com/erikras/ducks-modular-redux

2023-09-26 08:16 UTC, Sanya486 commented on src/api/fetchExchangeRates.js
> +    console.log(response)
Має працювати, але звісно перевірю

2023-09-28 09:18 UTC, merged